### ISSUE TITLE
How to contribute to this repo?

### ISSUE THREAD

**Issue by Enigmatisms** [taichi-dev/awesome-taichi#15]
Hi. I wonder if this repo accept recommendation (or PR of some sort). I've built a Taichi-lang based renderer that supports multiple PBR features, from volumetric tracers, BDPT to transient radiance renderer, etc. I believe the completeness should be appropriate, for this renderer to be categorized in **Renderer**. The repo can be found [here: AdaPT](https://github.com/Enigmatisms/AdaPT).

**Comment by yuanming-hu** [comment]
Hi, sure, we are accepting contributions! An example would be this: https://github.com/taichi-dev/awesome-taichi/pull/14/files

Thank you! AdaPT looks great!

**Comment by Enigmatisms** [comment]
Thanks! I'll be making a PR soon.
